### ISSUE TITLE
[BUG] Permission issues after mounting transcodes to tmpfs

### ISSUE THREAD

**Issue by GoingTime** [linuxserver/docker-jellyfin#265] opened 2024-09-07 12:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use docker compose to deploy jellyfin. When I mount `tmpfs `to `/config/cache/transcodes`, I notice that all the owners and groups of the` /config/cache` directory in jellyfin are `abc`, and only the owner and group of transcodes are `root`, and the permissions are `drwxrwx---`，which causes ffmpeg to have no permission to access the transcodes directory.

This is an inconsistent behavior. For newly created folders, some are owned by root and some are owned by abc. For folder permissions, some are drwxrwx--- and some are drwxr-xr-x, which will lead to confusing permission problems.

I suggest using some kind of script to automatically configure the owner and permissions of the newly mounted folder when jellfyin is initialized to avoid permission problems. Or recheck the code related to owner and permission configuration.

### Steps To Reproduce

```
# docker compose

version: "3.8"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=568
      - PGID=568
      devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/containers/jellyfin:/config
      - /mnt/videos:/data/videos
      - type: tmpfs
        target: /config/cache/transcodes
        tmpfs:
          size: 8G
```
```
# ls -l /config/cache

drwxrwx---  5 abc  abc    5 Sep  7 19:52 attachments
drwxrwx--- 29 abc  abc   29 Sep  7 19:31 audiodb-artist
drwxrwx--- 15 abc  abc   15 Sep  7 19:29 extracted-audio-images
drwxrwx---  3 abc  abc    3 Sep  7 19:36 images
drwxrwx---  2 abc  abc    3 Sep  7 19:32 imagesbyname
drwxrwx---  2 abc  abc   16 Sep  7 19:30 omdb
drwxrwx---  2 abc  abc  196 Sep  7 19:41 temp
drwxrwx---  2 root root  40 Sep  7 20:32 transcodes
```

```
# ls -l /data
total 1
drwxr-xr-x 3 root root 3 Sep  7 20:32 videos
```

### Environment

```markdown
- OS: TrueNAS SCALE 24.10 BETA.1 base Debian 12
```

### CPU architecture

x86-64

### Docker creation

```bash
Please see "Steps To Reproduce".
```

### Container logs

```bash
null
```

**Comment by latel** [comment] 2024-10-28 14:22
@GoingTime FYI, I solved this by adding `--tmpfs /config/cache/transcodes:uid=99,gid=100` according to https://github.com/docker/compose/issues/3425#issuecomment-423091370, change uid and gid as you need.

**Comment by drizuid** [comment] 2024-12-23 16:13
issue was caused by OP mounting tmpfs as root, no reply from OP after another users showed them how to mount using the uid/gid. Closing as non-reproducible by us.

**Closed by drizuid** 2024-12-23 16:13 UTC
Labels: no-issue-activity
