### ISSUE TITLE
library scan hangs in only linuxserver docker container

### ISSUE THREAD

**Issue by Motophan** [linuxserver/docker-jellyfin#4] opened 2019-07-30 04:51 UTC
https://github.com/jellyfin/jellyfin/issues/1531

Developer could not reproduce this issue outside of a docker container. AIO solutions pull from your repo instead of jellyfin's so it currently breaks plexguide and cloudbox.

**Comment by tobbenb** [comment] 2019-07-30 07:56
How do you expect us to fix it, if the developers aren't able to fix it?

**Comment by j0nnymoe** [comment] 2019-07-30 07:59
This is the first time report we've had of this issue.

Please provide the following information:
Host OS
Docker run or docker-compose information
Container Logs
Jellyfin log as and when the library scan hangs.

**Comment by CHBMB** [comment] 2019-07-30 11:16
@Motophan So does this reproduce it as suggested [here?](https://github.com/jellyfin/jellyfin/issues/1531#issuecomment-510815294)

In which case I'm not sure we can fix this and looks more upstream to me.

I'm not sure what you mean by AIO solutions.  If they're downstream projects then not much I can do about that to be honest.

**Comment by CHBMB** [comment] 2019-07-30 11:27
Also going down the rabbit hole.   You mentioned [here](https://github.com/jellyfin/jellyfin/issues/1545#issuecomment-516249342) that this has been an issue since v9.3?

Which kind of points to it being an upstream issue again as we didn't have a container for v9.3

At the moment it looks like nobody is really sure why this is occurring and I can't see that you've identified it only happening to our container with the troubleshooting documented thus far.  I'm happy if we get more information but I don't see we can do anything with what you've given us this far.

Maybe @anthonylavado could provide some more information?

**Comment by anthonylavado** [comment] 2019-07-30 12:24
@CHBMB We have an idea as to how this might be occurring, but it is very much in our project at the moment.

We’ve got a test build we’ll be making to see if it helps.

**Comment by CHBMB** [comment] 2019-07-30 19:47
@anthonylavado Thanks for that.  I'll leave this issue open for now and if you need anything from us, let us know.

**Comment by dag420** [comment] 2019-08-16 03:24
Anthonylavado suggestion to block TVDB fixes this. To anyone looking to make library scans complete: go to your libraries, click advanced, turn off TVDB for everything. Enable other metadata pullers.

**Comment by CHBMB** [comment] 2019-08-19 19:28
Closing this, as the upstream fix has been merged.

**Closed by CHBMB** 2019-08-19 19:28 UTC
