### ISSUE TITLE
Hardware acceleration isn't working properly

### ISSUE THREAD

**Issue by fengapappit** [linuxserver/docker-jellyfin#26] opened 2020-03-30 19:15 UTC
## Expected Behavior
Enabling VAAPI hardware acceleration in Jellyfin should work in its default configuration.

## Current Behavior
First issue is with the default transcode directory.
As it does not exist and Jellyfin doesn't create it, it's impossible to use the default configuration.

Secondly, once the devices are setup according to my host, the default user is not able to access them.
Any transcode attempt leads to the following error message:

```
/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"/jellyfin/media/12 Angry Men (1957)/12 Angry Men (1957) Bluray-1080p.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi  -b:v 10201576 -maxrate 10201576 -bufsize 20403152 -profile:v high -level 41  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -vf "format=nv12|vaapi,hwupload,scale_vaapi=format=nv12" -copyts -vsync -1 -codec:a:0 aac -strict experimental -ac 1 -ab 192000  -f hls -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/cache/temp/69e65dd7670476af5b32268cf32dcb6f%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/cache/temp/69e65dd7670476af5b32268cf32dcb6f.m3u8"


ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --toolchain=hardened --prefix=/usr --target-os=linux --enable-cross-compile --extra-cflags=--static --enable-gpl --enable-static --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --enable-omx --enable-omx-rpi --enable-version3 --enable-vaapi --enable-vdpau --arch=amd64 --enable-nvenc --enable-nvdec --enable-amf
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[AVHWDeviceContext @ 0x563fc93af5c0] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument
```

When running the same exact command through a root shell to the docker, it works as expected and transcoding works.

I've tried adding the abc user to the video group, doesn't change anything.

Same thing for running the docker container as high privilege.

I wanted to try running the service as root but I can't find what is starting the service nor where I can configure this. I got lost in /etc/s6 as I'm completely unfamiliar with it.

## Steps to Reproduce

1. Enable VAAPI transcoding in Playback options and save the settings
2. Notice that it gives an error concerning the transcode directory
3. Re-enable VAAPI and change the directory to something existing, such as /config/cache/temp/ and save the settings
4. Try playing anything needing transcode

## Environment
**OS:**     

Synology DSM 6.2.2-24922 Update 4
 
**CPU architecture:** 

INTEL Celeron J3455
      
**How docker service was installed:**      

Docker was installed through Synology store. Same for the image.
Since it does not support custom configuration, especially the devices, I had to import the following configuration file to make it work:

```
{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "",
   "cpu_priority" : 50,
   "devices" :  [
	   { 
		   "CgroupPermissions": "rwm", 
		   "PathInContainer": "/dev/dri/renderD128", 
		   "PathOnHost": "/dev/dri/renderD128" 
	   },
	   { 
		   "CgroupPermissions": "rwm", 
		   "PathInContainer": "/dev/dri/card0", 
		   "PathOnHost": "/dev/dri/card0" 
	   }
   ],
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enabled" : false,
   "entrypoint_default" : "/init",
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "HOME",
         "value" : "/root"
      },
      {
         "key" : "LANGUAGE",
         "value" : "en_US.UTF-8"
      },
      {
         "key" : "LANG",
         "value" : "en_US.UTF-8"
      },
      {
         "key" : "TERM",
         "value" : "xterm"
      },
      {
         "key" : "NVIDIA_DRIVER_CAPABILITIES",
         "value" : "compute,video,utility"
      },
      {
         "key" : "PGID",
         "value" : "101"
      },
      {
         "key" : "PUID",
         "value" : "1026"
      }
   ],
   "exporting" : false,
   "id" : "851b673d1b03caae27ad79561568172a9b7b8525bd01687582b85927686deef3",
   "image" : "linuxserver/jellyfin:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "linuxserver-jellyfin-latest",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 8096,
         "host_port" : 0,
         "type" : "tcp"
      },
      {
         "container_port" : 8920,
         "host_port" : 0,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/test",
         "mount_point" : "/jellyfin/media",
         "type" : "rw"
      }
   ]
}

```

## Command used to create docker container (run/create/compose/screenshot)

![image](https://user-images.githubusercontent.com/6908355/77951423-55671280-72ca-11ea-80a5-08a05cc6f1ae.png)

The previously mentioned configuration pretty much maps to a docker compose command.

I'd be glad if you could provide a tip in changing the user running the Jellyfin service from abc to root as a quick fix, as everything I've tried didn't work.

**Comment by aptalca** [comment] 2020-03-30 19:42
No vaapi support on arm64. It's for Intel gpus

**Comment by fengapappit** [comment] 2020-03-30 20:04
> No vaapi support on arm64. It's for Intel gpus

My bad, I read amd64. It is indeed an intel CPU with integrated graphics. I'll correct the post.

**Comment by Artiume** [comment] 2020-04-07 11:13
So 10.5.X0 has some issues that we're working out. It requires non-free drivers to work right now. 
Try this 

```
sudo docker exec -it -u 0 jellyfin echo "deb http://http.us.debian.org/debian stable main contrib non-free" | sudo tee -a /etc/apt/sources.list
sudo docker exec -it -u 0 jellyfin apt update
sudo docker exec -it -u 0 jellyfin apt install i945-va-driver-shaders
```

https://packages.debian.org/sid/i965-va-driver-shaders

**Comment by fengapappit** [comment] 2020-04-07 12:29
That's what I ended up doing on the official docker, but how come that it
works using the root account but not the normal one on your docker build ?

That broke my mind for days before having to cut my losses and let Jellyfin
win the battle for a while.

**Comment by Artiume** [comment] 2020-04-07 12:32
So if root works but the user doesn't, that breaks down to a simple permissions issue. Did you add the user to the video group?

**Comment by fengapappit** [comment] 2020-04-07 12:49
Yes, I've tried it. Didn't change anything unfortunately.

**Comment by aptalca** [comment] 2020-04-07 12:52
It's likely not working because you're not following our samples in the readme. You need to pass the device "--device /dev/dri", instead of passing render and card0 separately

**Comment by Artiume** [comment] 2020-04-07 12:52
Try chmod 777 the devices and see what happens. Maybe the libraries have perm issues as well.

I'm not familiar with DSM so it might be something else I'm not aware of

**Comment by Legogris** [comment] 2020-04-13 05:05
@aptalca There was a 10.5.4 release today that fixes a regression issue with VAAPI for MPEG 4: https://github.com/jellyfin/jellyfin/pull/2821

**Comment by TwoBall** [comment] 2020-04-21 11:24
I think it is because the set PUID does not have permission.
Synology's `/dev/dri/renderD128` permissions are `crw------- 1 root root` ,and PGID specified user group does not have permission to RW
I try to use `chmod 666 /dev/dri/renderD128` solved this problem，But every time Synology restarts, the permissions will be restored.
This is not a problem with jellyfin, because I use Emby-docker will also have this problem, but Emby SPK does not have this problem, it will set the permissions.

**Comment by aptalca** [comment] 2020-04-21 13:05
The permissions are automatically fixed as long as the mount points are as suggested in our readmes

**Comment by fmanno** [comment] 2020-04-22 22:32
> The permissions are automatically fixed as long as the mount points are as suggested in our readmes

I've ran into this exact same issue today unfortunately this is not true. I've created the container as per the readme, like this:
```
sudo docker create \
  --name=jellyfin \
  -e PUID=1002 \
  -e PGID=100 \
  -e TZ=Europe/London \
  -p 8096:8096 \
  -v /share/appdata/jellyfin:/config \
  -v /share/Media:/data \
  --device /dev/dri:/dev/dri \
  --restart unless-stopped \
  linuxserver/jellyfin
```
and I've also tried:
```
sudo docker create \
  --name=jellyfin \
  -e PUID=1002 \
  -e PGID=100 \
  -e TZ=Europe/London \
  -p 8096:8096 \
  -v /share/appdata/jellyfin:/config \
  -v /share/Media:/data \
  --device /dev/dri/renderD128:/dev/dri/renderD128 \
  --device /dev/dri/card0:/dev/dri/card0 \
  --restart unless-stopped \
  linuxserver/jellyfin
```
and permissions of the devices, in both cases, are:
```
# ls -al /dev/dri
total 0
drwxr-xr-x 2 root root       80 Apr 22 23:13 .
drwxr-xr-x 6 root root      360 Apr 22 23:13 ..
crw------- 1 root root 226,   0 Apr 22 23:13 card0
crw------- 1 root root 226, 128 Apr 22 23:13 renderD128
```

After running:
`# chmod 777 /dev/dri/*`

Transcoding works as expected. Perhaps this is the same problem as [this plex issue #207](https://github.com/linuxserver/docker-plex/issues/207)

**Comment by aptalca** [comment] 2020-04-22 22:50
Are these all synology's? What kind of Mickey Mouse stuff is this with the video devices root owned and no group rw?

There is nothing we can do for that scenario, you gotta fix the perms on host and report it to synology

**Comment by fmanno** [comment] 2020-04-22 23:24
In my case it's a Qnap TS-251+ NAS, I understand your point @aptalca, it's impossible to cater for all corner cases. I really appreciate all the work you guys do so we can use these apps.

Do you think perhaps this is worth a mention in the readme though?

For anybody else looking for a workaround, the containers are setup to run custom scripts at init (also not in the readme, maybe it could be included?) so I just created a script in:
/config/custom-cont-init.d/fix-dri-permissions (this is the container path)
```
#!/usr/bin/with-contenv bash

# check for the existence of a video device
if [ -e /dev/dri ]; then
    echo "Running: chmod 755 /dev/dri/*"
    chmod 755 /dev/dri/*
else
    exit 1
fi
```

And it now works and should be persistent if I ever update the container as long as I map the same host folder to the container /config folder.

**Comment by aptalca** [comment] 2020-04-22 23:49
Yeah, we'll update the info. Thanks for letting us know

**Comment by michaelkrieger** [comment] 2020-06-17 15:48
Chiming in on this one, I have a vanilla Debian installation.
Created a 'jellyfin' user as ID 1001 and 'jellyfin' group as ID 1001.

```
# groups jellyfin
jellyfin : jellyfin video render

# ls -l /dev/dri/
total 0
drwxr-xr-x  2 root root         80 Jun 17 11:35 by-path
crw-rw----+ 1 root video  226,   0 Jun 17 11:35 card0
crw-rw----+ 1 root render 226, 128 Jun 17 11:35 renderD128
```

Then a docker-compose.xml (excerpts)
```
    user: 1001:1001
    devices:
      - /dev/dri:/dev/dri
```

Running `/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel debug -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -i *.mp4 -f null -` results in
```
Applying option vaapi_device (set VAAPI hardware device (DRM path or X11 display name)) with argument /dev/dri/renderD128.
[AVHWDeviceContext @ 0x56408d606880] Failed to open /dev/dri/renderD128 as DRM device node.
[AVHWDeviceContext @ 0x56408d606880] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument
```

Only solution that seems to work is to `chmod o+rw /dev/dri/*` which I'd certainly prefer not to do.

Does this not have the correct group permissions for both video and render groups in this case?  I'm struggling to find why it lacks the appropriate permissions.

**Comment by michaelkrieger** [comment] 2020-06-17 16:18
Chiming in on this one, I have a vanilla Debian installation.
Created a 'jellyfin' user as ID 1001 and 'jellyfin' group as ID 1001.

```
# groups jellyfin
jellyfin : jellyfin video render

# ls -l /dev/dri/
total 0
drwxr-xr-x  2 root root         80 Jun 17 11:35 by-path
crw-rw----+ 1 root video  226,   0 Jun 17 11:35 card0
crw-rw----+ 1 root render 226, 128 Jun 17 11:35 renderD128
```

Then a docker-compose.xml (excerpts)
```
    user: 1001:1001
    devices:
      - /dev/dri:/dev/dri
```

Running `/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel debug -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -i *.mp4 -f null -` results in
```
Applying option vaapi_device (set VAAPI hardware device (DRM path or X11 display name)) with argument /dev/dri/renderD128.
[AVHWDeviceContext @ 0x56408d606880] Failed to open /dev/dri/renderD128 as DRM device node.
[AVHWDeviceContext @ 0x56408d606880] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument
```

Only solution that seems to work is to `chmod o+rw /dev/dri/*` which I'd certainly prefer not to do.  Meanwhile if I `su - jellyfin` (outside of the docker container) I can use those files without trouble, but in going into the docker container they are unusable unless world rw.

Does this not have the correct group permissions for both video and render groups in this case?  I'm struggling to find why it lacks the appropriate permissions.

**Comment by Legogris** [comment] 2020-06-18 00:57
Food for though for those who are having problems with permissions: Does running via podman (still using this image) instead of via docker make it easier to secure things?

**Comment by ageekhere** [comment] 2020-12-14 11:27
Just upgraded ubuntu to 20.04.1 LTS from 18.04 LTS and hardware acceleration stopped working.
sudo chmod 666 /dev/dri/renderD128 fixed the issue.

**Comment by ocervell** [comment] 2020-12-18 22:42
@Artiume I believe the cmds you copied would fix my problem, but when I try to add the repo, I get:
```
W: GPG error: http://http.us.debian.org/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 04EE7237B7D453EC NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY DCC9EFBF77E11517
```

**Comment by Artiume** [comment] 2020-12-18 23:18
we updated the key so make sure you have the right key now.

`wget -O - https://repo.jellyfin.org/debian/jellyfin_team.gpg.key | sudo apt-key add -`
`echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/debian $( lsb_release -c -s ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list`

**Comment by ocervell** [comment] 2020-12-19 00:00
mmh, getting other errors ...
```
Err:5 https://repo.jellyfin.org/debian focal Release
  404  Not Found [IP: 68.183.204.194 443]
Reading package lists... Done
E: The repository 'https://repo.jellyfin.org/debian focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
The second one I can manage with `--allow-unauthenticated`, but the IP not found I'm not sure ...

The line in `etc/apt/sources.list.d/jellyfin.list` looks like this:
`deb [arch=amd64] https://repo.jellyfin.org/debian focal main`

**Comment by ocervell** [comment] 2020-12-19 00:18
@Artiume it did not change the issue I had above, which I believe is related to `http://http.us.debian.org/debian` repo, not the Jellyfin repo.

**Comment by Artiume** [comment] 2020-12-19 00:28
So is this being done on the host or within the container? afaik the lsio container should be updated to the new key.

**Comment by ocervell** [comment] 2020-12-19 00:35
Ok, I managed to fix the key problem by running:
```
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
Executing: /tmp/apt-key-gpghome.8XdSbMqvNU/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
gpg: key E0B11894F66AEC98: 14 signatures not checked due to missing keys
gpg: key E0B11894F66AEC98: public key "Debian Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org>" imported
gpg: Total number processed: 1
gpg:               imported: 
apt update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Hit:4 http://http.us.debian.org/debian stable InRelease
Hit:5 https://repo.jellyfin.org/ubuntu bionic InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
191 packages can be upgraded. Run 'apt list --upgradable' to see them.
```
but I still cannot install `i945-va-driver-shaders` ....
```
# apt install i945-va-driver-shaders
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package i945-va-driver-shaders
```

**Comment by hotio** [comment] 2020-12-19 00:40
You can't install a non existing package...

**Comment by ocervell** [comment] 2020-12-19 13:40
Whoops ! @Artiume you might want to correct your existing comment to `i965-va-driver-shaders`.
Ok, so I managed to install it. But I'm now getting the same error as OP:
```
[AVHWDeviceContext @ 0x55c6c2ed3780] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument
```

**Comment by ocervell** [comment] 2020-12-19 14:59
Edit: it's working ! Had to enable hardware transcoding for h264 as well as HEVC in Jellyfin settings ...

**Comment by AlexKalopsia** [comment] 2021-05-18 20:31
Running on the same issue and yup, I "solved" it by running `chmod 777 /dev/dri/*` as suggested by @fmanno 

Is there any way to make this fix somehow permanent? I am also on a Syno.

**Comment by imavroukakis** [comment] 2021-06-19 07:36
> Running on the same issue and yup, I "solved" it by running `chmod 777 /dev/dri/*` as suggested by @fmanno
> 
> Is there any way to make this fix somehow permanent? I am also on a Syno.

Have you tried using Task Scheduler?
![image](https://user-images.githubusercontent.com/1764981/122634970-1c86a980-d0d9-11eb-89a0-7641ede22993.png)

![image](https://user-images.githubusercontent.com/1764981/122635020-5192fc00-d0d9-11eb-9efd-fcd346e9ef37.png)

Trying it out myself now

**Comment by rightsaidfred99** [comment] 2021-06-20 01:08
> 
> 
> Running on the same issue and yup, I "solved" it by running `chmod 777 /dev/dri/*` as suggested by @fmanno
> 
> Is there any way to make this fix somehow permanent? I am also on a Syno.

Help a noob out, where do I enter this command in? The Terminal in the Docker Container in Synology?

**Comment by AlexKalopsia** [comment] 2021-06-20 06:23
You can either do it from terminal establishing an SSH connection (you will find plenty tutorials for Syno), or just creating a scheduled task (like shown above ) and putting just that code in

**Comment by rightsaidfred99** [comment] 2021-06-20 06:37
Thanks, I did that and it works now. 

Although Intel Quick Sync seems to be very slow for me. The videos, especially 4k are transcoding, but on a DS918+, it stutters every 5 seconds and is pretty much unwatchable. 

20 June 2021, 16:23 by ***@***.***:

**Comment by imavroukakis** [comment] 2021-06-20 08:42
> > Running on the same issue and yup, I "solved" it by running `chmod 777 /dev/dri/*` as suggested by @fmanno
> > Is there any way to make this fix somehow permanent? I am also on a Syno.
> 
> Have you tried using Task Scheduler?
> ![image](https://user-images.githubusercontent.com/1764981/122634970-1c86a980-d0d9-11eb-89a0-7641ede22993.png)
> 
> ![image](https://user-images.githubusercontent.com/1764981/122635020-5192fc00-d0d9-11eb-9efd-fcd346e9ef37.png)
> 
> Trying it out myself now

That worked great over a reboot. @ondrejmo perhaps you have a better suggestion?

**Comment by ocervell** [comment] 2021-10-04 14:38
+1 on @rightsaidfred99 comment, hardware acceleration works but for 4k files I get stutter every 5 seconds if quality is set to any high preset than 1080 - 20Mbps... My network bandwith is 1Gb and have a decent Synology DS920+ NAS.

**Comment by j0nnymoe** [comment] 2022-06-29 21:26
Closing this as lots has changed since this was originally opened in terms of the drivers and hardware acceleration.

Please re-open a fresh ticket if this is still an issue.

**Closed by j0nnymoe** 2022-06-29 21:26 UTC
Labels: no-issue-activity
