### ISSUE TITLE
Intel QuickSync on Docker/Debian 11 (TrueNAS Scale) not working: Device creation failed: -5 with qsv=hw

### ISSUE THREAD

**Issue by allthesebugsv2** [linuxserver/docker-jellyfin#109] opened 2021-05-05 19:15 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

QuickSync hardware acceleration should work.

## Current Behavior

Videos are not playing with QuickSync enabled. 
After disabling hardware acceleration they work fine.
VAAPI also works fine.

## Steps to Reproduce

Note that I first had to delete the outdated library file according to #107 
1. Try to play a video which needs transcoding with QSV enabled
2. Jellyfin displays an error that the media cannot be played
3. Manually execute the command Jellyfin used to transcode the video
4. Get the the error message I pasted below

## Environment
**OS:** Debian 11 (TrueNAS Scale)
**CPU architecture:** Intel J5040
**How docker service was installed:** Comes preinstalled from the distro repo
**Docker Container Version** Jellyfin 10.7.5 (last pulled on 5th May 21)

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1003
      - PGID=1005
      - UMASK_SET=<022>
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /storage/jellyfin:/config
      - /pool/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 
      - 7359:7359/udp 
      - 1900:1900/udp 
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped

```
## Docker logs

Error when trying to play a movie with 
> /usr/lib/jellyfin-ffmpeg/ffmpeg -c:v hevc_qsv -init_hw_device qsv=hw ...
```
ffmpeg version 4.3.1-Jellyfin Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[AVHWDeviceContext @ 0x55a420d7dc00] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so has no function __vaDriverInit_1_0
[AVHWDeviceContext @ 0x55a420d7dc00] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value 'qsv=hw' for option 'init_hw_device': Input/output error
Error parsing global options: Input/output error
```
vainfo on the host
```
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```
vainfo inside the container
```
libva info: VA-API version 1.11.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_11
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.11 (libva 2.11.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.3 (bec8e13)
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```

**Comment by foux** [comment] 2021-05-06 12:15
Got the same issue since last update, was working perfectly before

**Comment by foux** [comment] 2021-05-06 12:25
Switching back to v10.7.2, and the HW encoding works again. But installing Jellyfin 10.7.5 outside of LS Docker works perfectly

**Comment by foux** [comment] 2021-05-06 13:03
Probably an upstream error, as I've got the same using the Jellyfin image. Created this issue jellyfin/jellyfin#5993

**Comment by allthesebugsv2** [comment] 2021-05-06 17:57
@foux 
I think your error might be a different one as your error message is not the same
Also, I get the same results on previous Jellyfin versions.

**Comment by gldl137** [comment] 2021-05-07 07:55
We have the same problem

> @foux
> 我认为您的错误可能是不同的，因为您的错误消息并不相同
> 此外，在以前的Jellyfin版本中，我得到的结果也是相同的。

**Comment by mLgz0rn** [comment] 2021-05-09 14:02
same problem here

**Comment by a-usov** [comment] 2021-05-10 16:17
Seems like it was automatically downgraded in this [commit](https://github.com/linuxserver/docker-jellyfin/commit/ede49b23395ac766f811e1466a452ea04579e1e1)

**Comment by aptalca** [comment] 2021-05-10 16:20
That's what the jellyfin repo provided as jellyfin-ffmpeg is a dependency of jellyfin

**Comment by aptalca** [comment] 2021-05-10 16:56
Here's the latest package check build log and when we requested jellyfin 10.7.5-1, repo provided jellyfin-ffmpeg 4.3.1-4-focal
https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-jellyfin/detail/master/295/pipeline/123#step-136-log-226

**Comment by allthesebugsv2** [comment] 2021-05-12 17:35
I can confirm that deleting the outdated library file according to #107 and then installing jellyfin-ffmpeg_4.3.2-1-focal fixes QSV for me

**Comment by ZachMayry** [comment] 2021-05-13 15:50
I hard to hardcode the tag `10.7.2-1-ls110` to get QSV to work again

**Comment by Ulrar** [comment] 2021-05-15 09:15
Thanks @allthesebugsv2, my fix in #107 was working until now but this morning it broke again. I can confirm that upgrading jellyfin-ffmpeg manually to 4.3.2-1 focal does indeed solve the problem, I hope this can be packaged in the next version of the image or it's going to break again on every update.

For those looking for it, here's how you manually upgrade it : 
```
docker exec -it jellyfin /bin/bash
wget https://repo.jellyfin.org/releases/server/ubuntu/versions/jellyfin-ffmpeg/4.3.2-1/jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb
dpkg -i jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb
```

That's coming from the official jellyfin repo so it should be safe, but you'll have to do that after each update until this new version is packaged into the docker image upstream.

**Comment by edwardwong80** [comment] 2021-05-17 12:51
> Thanks @allthesebugsv2, my fix in #107 was working until now but this morning it broke again. I can confirm that upgrading jellyfin-ffmpeg manually to 4.3.2-1 focal does indeed solve the problem, I hope this can be packaged in the next version of the image or it's going to break again on every update.
> 
> For those looking for it, here's how you manually upgrade it :
> 
> ```
> docker exec -it jellyfin /bin/bash
> wget https://repo.jellyfin.org/releases/server/ubuntu/versions/jellyfin-ffmpeg/4.3.2-1/jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb
> dpkg -i jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb
> ```
> 
> That's coming from the official jellyfin repo so it should be safe, but you'll have to do that after each update until this new version is packaged into the docker image upstream.

Interesting fact is, Jellyfin on Debian has a newer FFMPEG version than Ubuntu, which makes me feeling weird.

**Comment by marine1988** [comment] 2021-05-24 12:42
i have the same problem

**Comment by Hukuma1** [comment] 2021-06-06 19:17
Still happening. Or rather again? (did an update to container)

To fix inability to transcode update jellyfin-ffmpeg to `4.3.2-1`.

My Linuxserver Jellyfin container didn't have `wget` installed, so we can use `curl`:

```
docker exec -it jellyfin /bin/bash
curl -LO https://repo.jellyfin.org/releases/server/ubuntu/versions/jellyfin-ffmpeg/4.3.2-1/jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb
dpkg -i jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb
```

**Comment by FrederikHaa** [comment] 2021-06-07 10:14
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

By creating a 'custom-cont-init.d' folder in the /config directory, and then inside that folder creating a bash script with the curl and dpkg commands, it will be executed everytime you recreate the image. I.e. you don't have to manually update ffmpeg.

**Comment by Ulrar** [comment] 2021-06-11 14:33
Hi,

Thanks @FrederikHaa, I wasn't aware of that feature, it works like a charm.
This issue though should stay open as this is only a workaround, the version of ffmpeg shipping in the container image should still be fixed.

**Comment by Roxedus** [comment] 2021-06-11 14:38
We install the version jellyfin sets as a dependency, it's not something *we* control. 

> version of ffmpeg shipping in the container image should still be fixed

**Comment by Hukuma1** [comment] 2021-06-11 18:02
> We install the version jellyfin sets as a dependency, it's not something _we_ control.
> 
> > version of ffmpeg shipping in the container image should still be fixed

Can we please get a link to the place we need to submit this issue to?

**Comment by FuzzyMistborn** [comment] 2021-06-11 18:06
Already reported here https://github.com/jellyfin/jellyfin/issues/5993

**Comment by Ulrar** [comment] 2021-09-16 14:35
Looks like there's a new problem that requires downgrading the driver, here's a updated script for anyone who started having problems again recently : 

```bash
$ cat /config/custom-cont-init.d/update-ffmpeg.sh
```
```bash
#!/bin/bash
echo "**** Updating ffmpeg ****"
cd /tmp
curl -LO https://repo.jellyfin.org/releases/server/ubuntu/versions/jellyfin-ffmpeg/4.3.2-1/jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb
dpkg -i jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb

echo "**** Downgrading intel drivers ****"
curl -LO https://repositories.intel.com/graphics/ubuntu/pool/main/i/intel-media-driver-non-free/intel-media-va-driver-non-free_21.2.2+i593~u20.04_amd64.deb
dpkg -i intel-media-va-driver-non-free_21.2.2+i593~u20.04_amd64.deb
```

**Comment by FuzzyMistborn** [comment] 2021-10-18 02:18
Still an issue.

**Comment by ShadwDrgn** [comment] 2021-11-06 03:50
The solution to this seems like it would be to compile an ffmpeg specifically for the drivers this image ends up using so that we know for sure it'll always have the right hwaccel drivers and ffmpeg version.

**Comment by omeryagmurlu** [comment] 2021-11-17 23:15
Here’s an updated script for the unstable tag (10.8.0), for some reason a dependency for the driver is missing with default install.

```bash
#!/bin/bash
echo "**** Updating ffmpeg ****"
cd /tmp
curl -LO https://repo.jellyfin.org/releases/server/ubuntu/versions/jellyfin-ffmpeg/4.3.2-1/jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb
dpkg -i jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb

echo "**** Fixing intel drivers in place ****"
curl -LO https://repositories.intel.com/graphics/ubuntu/pool/main/i/intel-gmmlib/libigdgmm11_21.2.2+i620~u20.04_amd64.deb
dpkg -i libigdgmm11_21.2.2+i620~u20.04_amd64.deb
curl -LO https://repositories.intel.com/graphics/ubuntu/pool/main/i/intel-media-driver-non-free/intel-media-va-driver-non-free_21.2.2+i593~u20.04_amd64.deb
dpkg -i intel-media-va-driver-non-free_21.2.2+i593~u20.04_amd64.deb
```

**Comment by brunsy** [comment] 2021-11-24 07:01
@omeryagmurlu Another combination you could try is unstable (10.8.0) with @nyanmisaka's ffmpeg `4.4` and QSV `21.3.x` 
```
#!/bin/bash
cd /tmp

echo "**** Update drivers to 21.3.1  ****"
curl -s https://repositories.intel.com/graphics/intel-graphics.key | apt-key add -
echo 'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main' > /etc/apt/sources.list.d/intel-graphics.list
apt-get update
apt-get install -y intel-media-va-driver-non-free unzip

echo "**** Update to jellyfin-ffmpeg_4.4 ****"
curl -Lo jellyfin-ffmpeg.zip https://nightly.link/nyanmisaka/jellyfin-ffmpeg/suites/3765849982/artifacts/92607185
unzip jellyfin-ffmpeg.zip
dpkg -i jellyfin-ffmpeg_4.4-1-focal_amd64.deb
```

**Comment by marine1988** [comment] 2021-12-24 04:34
any news?

**Comment by rightsaidfred99** [comment] 2022-01-23 02:41
this doesn't work, nothing does

**Comment by rightsaidfred99** [comment] 2022-01-23 03:02
> ```shell
> dpkg -i intel-media-va-driver-non-free_21.2.2+i593~u20.04_amd64.deb
> ```

We still get spinning cirlce and this;

[h264_qsv @ 0x557545827000] Error initializing the MFX video decoder: invalid video parameters (-15)
Error while decoding stream #0:1: Invalid argument

**Comment by rany2** [comment] 2022-02-23 10:37
This issue is still relevant.

**Comment by Ulrar** [comment] 2022-03-26 07:26
Still an issue

**Comment by ChillyEmber** [comment] 2022-04-01 21:35
definitely still an issue

**Comment by Hukuma1** [comment] 2022-06-11 19:51
Still happening on latest `10.8`.

**Comment by Ulrar** [comment] 2022-06-11 20:02
10.8 from linuxserver solves it from me, the updated ffmpeg and libs are working as expected

**Comment by nyanmisaka** [comment] 2022-06-11 20:04
> Still happening on latest `10.8`.

This shouldn't be an issue in 10.8 and jellyfin-ffmpeg5.

**Comment by j0nnymoe** [comment] 2022-06-11 20:11
Can confirm this is working (though not tested on TrueNAS Scale)

**Comment by Hukuma1** [comment] 2022-06-11 21:21
> > Still happening on latest `10.8`.
> 
> This shouldn't be an issue in 10.8 and jellyfin-ffmpeg5.

So I have an older `jellyfin-ffmpeg` in the latest Linuxserver Docker of Jellyfin `10.8`?

```
root@Jellyfin:/# /usr/lib/jellyfin-ffmpeg/ffmpeg
ffmpeg version 4.4.1-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
```

<img width="618" alt="settings" src="https://user-images.githubusercontent.com/54511555/173205130-04de49ba-98ce-4b74-8f2c-ff5de50510d5.png">

<img width="302" alt="server" src="https://user-images.githubusercontent.com/54511555/173205147-aa6c7783-05f1-4844-b86b-cb460405d2ec.png">

```
  jellyfin:
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=100
      - JELLYFIN_PublishedServerUrl=192.168.1.4
    hostname: Jellyfin
    image: linuxserver/jellyfin
```
Image:  https://hub.docker.com/layers/jellyfin/linuxserver/jellyfin/latest/images/sha256-efbae1e2cbe037cbecccbed3c1373bd615e8a91ade814b664a550e1264252964?context=explore

**Comment by j0nnymoe** [comment] 2022-06-11 22:54
Latest image has:
```
root@fa33318e74b6:/# /usr/lib/jellyfin-ffmpeg/ffmpeg
ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
```

**Comment by Ulrar** [comment] 2022-06-11 23:07
> > > Still happening on latest `10.8`.
> > 
> > 
> > This shouldn't be an issue in 10.8 and jellyfin-ffmpeg5.
> 
> So I have an older `jellyfin-ffmpeg` in the latest Linuxserver Docker of Jellyfin `10.8`?
> 
> ```
> root@Jellyfin:/# /usr/lib/jellyfin-ffmpeg/ffmpeg
> ffmpeg version 4.4.1-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
>   built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
> ```
> 
> <img alt="settings" width="618" src="https://user-images.githubusercontent.com/54511555/173205130-04de49ba-98ce-4b74-8f2c-ff5de50510d5.png">
> 
> <img alt="server" width="302" src="https://user-images.githubusercontent.com/54511555/173205147-aa6c7783-05f1-4844-b86b-cb460405d2ec.png">
> 
> ```
>   jellyfin:
>     container_name: jellyfin
>     devices:
>       - /dev/dri:/dev/dri
>     environment:
>       - PUID=1000
>       - PGID=100
>       - JELLYFIN_PublishedServerUrl=192.168.1.4
>     hostname: Jellyfin
>     image: linuxserver/jellyfin
> ```
> 
> Image: https://hub.docker.com/layers/jellyfin/linuxserver/jellyfin/latest/images/sha256-efbae1e2cbe037cbecccbed3c1373bd615e8a91ade814b664a550e1264252964?context=explore
> 
> Some HEVC content works, others show this:
> 
> ```
> [AVHWDeviceContext @ 0x55fb8014d8c0] Failed to get number of OpenCL platforms: -1001.
> Device creation failed: -19.
> Failed to set value 'opencl=ocl@va' for option 'init_hw_device': No such device
> Error parsing global options: No such device
> ```
> 
> When it works it looks normal like this:
> 
> ```
> Stream mapping:
>   Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_qsv))
>   Stream #0:1 -> #0:1 (aac (native) -> aac (native))
> ```

Did you forget to remove the script in the cont init folder that updated ffmpeg to fix it on 10.7 ?

**Comment by Hukuma1** [comment] 2022-06-12 01:20
Good tip! I did try something like that before, but it seems my folders were empty where those scripts would have gone (`custom-cont-init.d`, `custom-services.d`).

I ended up completely wiping the container and image and re-downloading it from scratch. That seems to have worked.

```
ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
```

So if anyone has the same issues try that. However, it still fails even with this newest version.

```
ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3 --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[AVHWDeviceContext @ 0x5606b8f7e180] Failed to get number of OpenCL platforms: -1001.
Device creation failed: -19.
Failed to set value 'opencl=ocl@va' for option 'init_hw_device': No such device
Error parsing global options: No such device
```

**Comment by Hukuma1** [comment] 2022-06-12 01:36
Sorry for the spam. Figured out the issue. I never had `- DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel` in my Docker Compose.

This allows the `VPP Tone mapping` to work (and my HDR HEVC transcode), but it looks a bit too dark. If I try to enable the other one (`Enable Tone Mapping`), it tells me the video is incompatible again. Is this an intended limitation or if VPP works so should the second method?

**Comment by nyanmisaka** [comment] 2022-06-12 06:49
> 

VPP TM only requires the built-in Intel media driver whereas OpenCL TM requires an extra compute-runtime (OpenCL mod).

VPP TM is a fixed function from Intel’s driver thus there’s no fine tuning options for colors and brightness like the OpenCL TM.

If the OpenCL TM fails the transcoding, there must be something wrong with the mod installation. Share your ffmpeg log please.

**Comment by j0nnymoe** [comment] 2022-06-29 21:54
Closing as this seems to be fixed and not a container issue.

**Closed by j0nnymoe** 2022-06-29 21:54 UTC
