### ISSUE TITLE
Jellyfin Service not starting

### ISSUE THREAD

**Issue by prayag17** [linuxserver/docker-jellyfin#91] opened 2021-01-09 11:19 UTC
Hello, I recently switched from rpi3 to rpi4(4gb) and installed Jellyfin on docker. If i use `linuxserver/jellyfin` jellyfin(service) wont start. The issue does not show up if i use `jellyfin/jellyfin`
Logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support the app dev(s) visit:,
Jellyfin: https://opencollective.com/jellyfin,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    0,
User gid:    0,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 40-gid-video: executing... ,
[cont-init.d] 40-gid-video: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
```

**Comment by Roxedus** [comment] 2021-01-09 11:51
Dupe of #90 #83 #75 and #71

**Closed** 2021-01-09 12:56 UTC

**Comment by prayag17** [comment] 2021-01-19 03:34
This still doesn't fix my issue.

**Comment by aptalca** [comment] 2021-01-19 03:40
`This` is not very descriptive

**Comment by prayag17** [comment] 2021-01-19 03:42
I have described my issue above

**Comment by prayag17** [comment] 2021-01-19 03:43
This happens with every Linux server image I use, this issue did not occur with rpi3

**Comment by Roxedus** [comment] 2021-01-19 03:44
And we provided a solution. Did you do any of the things in FAQ linked in those referenced issues?

**Comment by aptalca** [comment] 2021-01-19 03:44
I know, and the duplicate issues we linked provide you with 4 (four) different methods to fix it. You saying `still doesn't fix` leads me to believe you tried something that didn't work, which has nothing to do with what the original issue was.

**Comment by prayag17** [comment] 2021-01-19 03:47
Yes, I saw and tried the solution but it didn't work, my jellyfin image is fixed now but duckdns image is broken

**Comment by aptalca** [comment] 2021-01-19 03:49
`my jellyfin image is fixed now but duckdns image is broken`
And how does that outcome fit in with `This still doesn't fix my issue.` and `I have described my issue above`?

If you keep giving us random one liners that are not even accurate, we cannot help you.

**Comment by prayag17** [comment] 2021-01-19 03:52
Jellyfin image works some time only

**Comment by Roxedus** [comment] 2021-01-19 10:51
We still need more information than "doesnt work"
