### ISSUE TITLE
VAAPI not working on nuc gen 10

### ISSUE THREAD

**Issue by ShadwDrgn** [linuxserver/docker-jellyfin#121] opened 2021-07-20 00:19 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

https://repo.jellyfin.org/releases/server/ubuntu/versions/jellyfin-ffmpeg/4.3.2-1/jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb
needs to be installed on the latest jellyfin docker image to fix VAAPI not working. Once I install this deb my hardware transcoding starts working again.
------------------------------

## Expected Behavior
should be able to VAAPI hardware transcode all formats on a skull canyon intel nuc without shelling into the container and installing a package.

## Current Behavior
ffmpeg crashes due to versioning issues or something

## Steps to Reproduce

1. transcode a video
2. observe crash
3. install jellfin-ffmpeg latest
4. observe no crash this time

## Environment
**OS:**
whatever's in the docker container. focal i guess?
**CPU architecture:**
intel x86_64
**How docker service was installed:**
i don't remember? apt install docker i assume.
It's irrelevant though because i've included the fix here, so no need for you to troubleshoot.

## Command used to create docker container (run/create/compose/screenshot)

This seems unnecessary as well given i've provided the fix.
## Docker logs

see above.

**Comment by Roxedus** [comment] 2021-07-20 05:11
Dupe of #109 and #115

**Closed by Roxedus** 2021-07-20 05:11 UTC

**Comment by marine1988** [comment] 2021-10-15 13:56
last october version same issue e regret of buying this cpu all my docker containerts have issues with this intel 10th gen :(
