### ISSUE TITLE
Unable to add folders to library

### ISSUE THREAD

**Issue by crypdick** [linuxserver/docker-jellyfin#19] opened 2020-02-16 18:50 UTC
## Expected Behavior
Under Server  > Libraries > Add Media Library > Folders, clicking the + button should prompt for a directory.

## Current Behavior
The + button is unresponsive. All other elements on this screen are responsive.

## Steps to Reproduce
1. Fresh install of this docker image using CapRover. Settings below.
2. In initial set-up wizard, try to create library (fails).
3. Skip ahead without adding library. Log in, navigate to library settings and try again (fails).

## Environment
**OS:** Ubuntu Linux
**CPU architecture:** Unsure (Digital Ocean Droplet)
**How docker service was installed:**      Caprover

## Command used to create docker container (run/create/compose/screenshot)

P.S. I tested redundantly mounting to both `/data/` and `/media` as per #6 (according to @aptalca this shouldn't matter).

![Screenshot from 2020-02-16 13-40-30](https://user-images.githubusercontent.com/5415776/74610589-7bda4100-50c2-11ea-933f-076e5a4ceda3.png)

![Screenshot from 2020-02-16 13-41-02](https://user-images.githubusercontent.com/5415776/74610593-809ef500-50c2-11ea-9e79-c62935e8aa87.png)

## Docker logs
```

srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [s6-init] ensuring user provided files have correct perms...exited 0.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [fix-attrs.d] applying ownership & permissions fixes...
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [fix-attrs.d] done.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [cont-init.d] executing container initialization scripts...
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [cont-init.d] 01-envfile: executing... 
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [cont-init.d] 01-envfile: exited 0.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [cont-init.d] 10-adduser: executing... 
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | 
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | -------------------------------------
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |           _         ()
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |          | |  ___   _    __
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |          | | / __| | |  /  \ 
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |          | | \__ \ | | | () |
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |          |_| |___/ |_|  \__/
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | 
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | 
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | Brought to you by linuxserver.io
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | We gratefully accept donations at:
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | https://www.linuxserver.io/donate/
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | -------------------------------------
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | GID/UID
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | -------------------------------------
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | 
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | User uid:    0
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | User gid:    0
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | -------------------------------------
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | 
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [cont-init.d] 10-adduser: exited 0.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [cont-init.d] 30-config: executing... 
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [cont-init.d] 30-config: exited 0.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [cont-init.d] 40-gid-video: executing... 
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [cont-init.d] 40-gid-video: exited 0.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [cont-init.d] 99-custom-scripts: executing... 
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [custom-init] no custom files found exiting...
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [cont-init.d] 99-custom-scripts: exited 0.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [cont-init.d] done.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [services.d] starting services
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [services.d] done.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:47:59] [INF] Jellyfin version: 10.4.3
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:47:59] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:47:59] [INF] Operating system: Linux
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:47:59] [INF] Architecture: X64
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:47:59] [INF] 64-Bit Process: True
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:47:59] [INF] User Interactive: True
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:47:59] [INF] Processor count: 4
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:47:59] [INF] Program data path: /config/data
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:47:59] [INF] Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:47:59] [INF] Application directory: /usr/lib/jellyfin/bin/
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:47:59] [INF] Setting cache path to /config/cache
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:47:59] [INF] Loading assemblies
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:01] [INF] Kestrel listening on all interfaces
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:01] [INF] Running startup tasks
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:01] [INF] Daily trigger for Chapter image extraction set to fire at 02/17/2020 02:00, which is 7:11:58.6430558 from now.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:01] [INF] Found ffmpeg version 4.2.1
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:01] [INF] Available decoders: ["h264", "h264_cuvid", "hevc", "hevc_cuvid", "mpeg2video", "aac", "ac3", "mp3"]
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:01] [INF] Available encoders: ["libx264", "h264_nvenc", "h264_omx", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_nvenc", "hevc_vaapi", "mpeg4", "msmpeg4", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:01] [INF] FFmpeg: SetByArgument: /usr/lib/jellyfin-ffmpeg/ffmpeg
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:01] [INF] ServerId: c457ed9e44a04971abfde2a70c4201bd
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:02] [INF] Executed all pre-startup entry points in 0:00:00.5706027
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:02] [INF] Core startup complete
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:02] [INF] Executed all post-startup entry points in 0:00:00.2524262
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:04] [INF] StartupTrigger fired for task: Check for plugin updates
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:04] [INF] Queueing task PluginUpdateTask
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:04] [INF] Executing Check for plugin updates
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:05] [INF] Check for plugin updates Completed after 0 minute(s) and 0 seconds
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:05] [INF] ExecuteQueuedTasks
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:07] [ERR] Error sending socket message from 10.255.75.93 to 239.255.255.250:1900
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | System.Net.Sockets.SocketException (0xFFFFFFFF): Unknown error -1
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:07] [ERR] Error sending socket message from 10.255.75.93 to 239.255.255.250:1900
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | System.Net.Sockets.SocketException (0xFFFFFFFF): Unknown error -1
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:48:07] [ERR] Error sending socket message from 10.255.75.93 to 239.255.255.250:1900
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | System.Net.Sockets.SocketException (0xFFFFFFFF): Unknown error -1
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:49:02] [INF] Authentication request for d has succeeded.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:49:02] [INF] Creating new access token for user d63992ed-3395-4a94-b833-932de23ddc92
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:49:02] [ERR] Could not find handler for /socket
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:49:02] [ERR] Error processing request: Unable to find the specified file.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:49:07] [ERR] Error sending socket message from 10.255.75.93 to 239.255.255.250:1900
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | System.Net.Sockets.SocketException (0xFFFFFFFF): Unknown error -1
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:49:07] [ERR] Error sending socket message from 10.255.75.93 to 239.255.255.250:1900
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | System.Net.Sockets.SocketException (0xFFFFFFFF): Unknown error -1
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:49:07] [ERR] Error sending socket message from 10.255.75.93 to 239.255.255.250:1900
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | System.Net.Sockets.SocketException (0xFFFFFFFF): Unknown error -1
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:49:42] [ERR] Error registering endpoint
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | System.OperationCanceledException: The operation was canceled.
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.ApplicationHost.IsIpAddressValidAsync(IPAddress address, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.ApplicationHost.GetLocalIpAddressesInternal(Boolean allowLoopback, Int32 limit, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Dlna.Main.DlnaEntryPoint.RegisterServerEndpoints()
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Dlna.Main.DlnaEntryPoint.StartDevicePublisher(DlnaOptions options)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:50:07] [ERR] Error sending socket message from 10.255.75.93 to 239.255.255.250:1900
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | System.Net.Sockets.SocketException (0xFFFFFFFF): Unknown error -1
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:50:07] [ERR] Error sending socket message from 10.255.75.93 to 239.255.255.250:1900
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | System.Net.Sockets.SocketException (0xFFFFFFFF): Unknown error -1
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | [18:50:07] [ERR] Error sending socket message from 10.255.75.93 to 239.255.255.250:1900
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    | System.Net.Sockets.SocketException (0xFFFFFFFF): Unknown error -1
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
srv-captain--jellyfin.1.v1wduilwds6u@caprover-ubuntu-s-1vcpu-3gb-sfo2-01    |    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
```

**Comment by crypdick** [comment] 2020-02-16 19:02
Output in Firefox console when I click on the + button:

```
app is hidden apphost.js:203:21
triggering app resume event apphost.js:195:21
opening web socket with url: wss://jellyfin.[REDACTED]
/socket?api_key=[REDACTED]&deviceId=[REDACTED] apiclientcore.js:351:225
Requesting url without automatic networking: https://jellyfin.[REDACTED].com/System/Info/Public apiclientcore.js:264:21
Requesting url without automatic networking: https://jellyfin.[REDACTED].com/Environment/DefaultDirectoryBrowser apiclientcore.js:264:21
Requesting url without automatic networking: https://jellyfin.[REDACTED].com/ScheduledTasks?IsEnabled=true apiclientcore.js:264:21
```

**Comment by aptalca** [comment] 2020-02-16 19:45
The issue seems to be whatever reverse proxy method caprover is using. It works fine when you connect directly to container and reverse proxy with the preset proxy conf in our letsencrypt image.

**Comment by crypdick** [comment] 2020-02-16 20:23
@aptalca I'm too n00by to really know how to even begin meddling with CapRover's reverse proxy confs. I tried to delete the app and rebuild it without Caprover's "Enable HTTPS" option, and I also experimented with enabling/disabling websocket support, but no dice.

**Comment by aptalca** [comment] 2020-02-16 20:35
In that case, introducing too many variables and complexities at once is not a good idea.

Let's take caprover out of the equation for starters. I have no experience with it, can't help you with it.

Try creating the container in command line via either the docker run/create we provide or the docker compose yml (I recommend docker compose) and confirm it works. Then you can try and replicate it in caprover if you like.

I'm closing this now since it's not a bug. Feel free to drop by our discord or forum for further help

**Closed by aptalca** 2020-02-16 20:35 UTC

**Comment by AkgunFatih** [comment] 2020-10-06 02:46
@crypdick Hi, can you share the template pls ?
