### ISSUE TITLE
Network error "could not find an available, non-overlapping IPv4 address pool..." when starting container

### ISSUE THREAD

**Issue by ioogithub** [linuxserver/docker-jellyfin#148] opened 2022-03-19 17:53 UTC
Using the default config with only the file paths modified. I get an error when running docker-compose up:
```
Creating network "docker-compose_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```

------------------------------

## Expected Behavior
I would expect the container would start.

## Current Behavior
I get the error then nothing happens.

## Steps to Reproduce
1. $ docker-compose up

## Environment
**OS:Ubuntu Server 21.10

**CPU architecture:arm64

**How docker service was installed:**
docker pull lscr.io/linuxserver/jellyfin

## Command used to create docker container (run/create/compose/screenshot)
docker-compose up

## Docker logs
There are no logs because the container does not start

## Other information:
- Jellyfin runs normally when using the native Ubuntu package but I would like to use this docker package.
- I have two other docker apps running successfully on this server so my docker installation is working.
- I brought them down to troubleshoot but it did not make any difference. I get the error when starting regardless.

## Other problems:
Note: I also tried using the Discord link however the invite is not valid:
"Invite Invalid" This invite may be expired or you may not have permission to join.
- I tried with two different browsers on two different networks, same result.

**Comment by TheSpad** [comment] 2022-03-19 18:19
This isn't a container issue, your host doesn't have any available unallocated private address space to assign to the container. You need to identify what docker networks you have, what ranges are in use, and what you can do to free up addresses.

Alternatively this can also be caused in some VPN configurations so if you're attempting to run Jellyfin through a VPN container that may be the cause but as you've neglected to provide your compose I can't tell.

**Closed by TheSpad** 2022-03-19 18:19 UTC
