### ISSUE TITLE
Connection Failure We're unable to connect to the selected server right now. 

### ISSUE THREAD

**Issue by grglzrv** [linuxserver/docker-jellyfin#131] opened 2021-11-18 08:33 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
ERROR:

We're unable to connect to the selected server right now. Please ensure it is running and try again.
------------------------------

## Expected Behavior
I am not able to log in after updating docker image to linuxserver/jellyfin:latest

## Steps to Reproduce
1. Install new Jellyfin server with version linuxserver/jellyfin:2021.11.17 or linuxserver/jellyfin:2021.11.18
2.  Create a new username
3. Update Jellyfin docker image to  linuxserver/jellyfin:latest and start Jellyfin server with the new image

## Environment
**OS:** Ubuntu 21.10
**CPU architecture:** x86_64
**How docker service was installed:**
with official docker script 

## Docker logs

[_Jellyfin_logs.txt](https://github.com/linuxserver/docker-jellyfin/files/7561268/_Jellyfin_logs.txt)

**Comment by drizuid** [comment] 2021-12-27 21:50
please fill out the full template and provide full docker logs, they begin with our ascii logo. Use pastebin (or similar) rather than text attachments.

**Comment by Hoohm** [comment] 2022-01-15 20:04
Having the same issue

**Comment by DevinCampbell** [comment] 2022-02-18 04:33
I am also having this issue. One notable thing is that I used to run a Jellyfin server but recently moved to a new Docker host. I created a new Docker container, but didn't bring over any configuration data. I pointed the container at the media directories and gave it a blank config directory. When I go to log into the GUI via HTTP it brings up the old server's name as an option, so I'm not sure where it is getting that from.

## Expected Behavior

I should be able to set up or sign into Jellyfin.
## Current Behavior

I access http://192.168.1.10:8096, see "Select Server" with "$name's jellyfin server" listed. I click on it, choose "Connect", and receive the error "We're unable to connect to the selected server right now. Please ensure it is running and try again."
## Steps to Reproduce


1. Run provided docker-compose.yml
2. Attempt to access via HTTP

## Environment
**OS: Ubuntu 21.10 Linux 5.13.0-28-generic**
**CPU architecture:** x86_64
**How docker service was installed:**


Docker Compose
## Command used to create docker container (run/create/compose/screenshot)

docker-compose.yml
```
networks:
    br0:
        driver: bridge

services:
    jellyfin:
        container_name: jellyfin
        env_file: /vdev1/docker/env_files/jellyfin.env
        hostname: jellyfin
        image: lscr.io/linuxserver/jellyfin
        networks:
            - br0
        ports:
          - 8096:8096
          - 8920:8920
          - 7359:7359/udp
          - 1900:1900/udp
        restart: unless-stopped
        volumes:
          - /directory/:/config
          - /directory/:/data/animated_movies
          - /directory/:/data/anime
          - /directory/:/data/anime_movies
          - /directory/:/data/cartoons
          - /directory/:/data/movies
          - /directory/:/data/tvshows
```
jellyfin.env
```
PUID=1003
PGID=1001
TZ="America/Chicago"
JELLYFIN_PublishedServerUrl=192.168.1.10
```
## Docker logs

```
$ docker logs jellyfin
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Jellyfin: https://opencollective.com/jellyfin

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1003
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-gid-video: executing...
[cont-init.d] 40-gid-video: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:13:41] [INF] [1] Main: Jellyfin version: 10.7.7
[22:13:41] [INF] [1] Main: Environment Variables: ["[JELLYFIN_PublishedServerUrl, 192.168.1.10]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_DATA_DIR, /config/data]"]
[22:13:41] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", "--webdir=/usr/share/jellyfin/web"]
[22:13:41] [INF] [1] Main: Operating system: Linux
[22:13:41] [INF] [1] Main: Architecture: X64
[22:13:41] [INF] [1] Main: 64-Bit Process: True
[22:13:41] [INF] [1] Main: User Interactive: True
[22:13:41] [INF] [1] Main: Processor count: 24
[22:13:41] [INF] [1] Main: Program data path: /config/data
[22:13:41] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
[22:13:41] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[22:13:42] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache
[22:13:42] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[22:13:42] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[22:13:42] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[22:13:42] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[22:13:42] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[22:13:42] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[22:13:44] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.7.7.0
[22:13:44] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.7.7.0
[22:13:44] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.7.7.0
[22:13:45] [INF] [1] Main: Kestrel listening on Any IP4 Address
[22:13:45] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
[22:13:45] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[22:13:45] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {bad8f201-268d-48be-87f7-6fb41c8e2378} may be persisted to storage in unencrypted form.
[22:13:45] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[22:13:45] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 02/18/2022 02:00, which is 3:46:14.2558702 from now.
[22:13:45] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 4.4.1
[22:13:45] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[22:13:45] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[22:13:45] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl"]
[22:13:45] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: SetByArgument: /usr/lib/jellyfin-ffmpeg/ffmpeg
[22:13:45] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 0cf853d75e7448fca64bd154412811bd
[22:13:46] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 172.18.0.5/16
[22:13:46] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.1572848
[22:13:46] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[22:13:46] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1640996
[22:13:46] [INF] [1] Main: Startup complete 0:00:04.9072604
[22:13:48] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[22:13:48] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
[22:13:48] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[22:13:49] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 0 seconds
[22:13:49] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

**Comment by DevinCampbell** [comment] 2022-02-18 04:43
Well it looks like after deleting the server listed I was able to go through the normal set up process for a new Jellyfin server. Not sure what that was about.

**Comment by j0nnymoe** [comment] 2022-06-29 21:42
Closing as no extra comments.

**Closed by j0nnymoe** 2022-06-29 21:42 UTC
Labels: no-issue-activity

**Comment by tuyennn** [comment] 2022-12-13 10:33
@j0nnymoe same issue could you reopen this

https://user-images.githubusercontent.com/4010395/207293950-faacfd58-cad1-4f03-9aba-8904d9e6a488.mp4

**Comment by LoneExile** [comment] 2023-01-16 08:47
I fixed it by clearing local storage data in Devtools.

![image](https://user-images.githubusercontent.com/82561297/212633681-0e7c3a31-6ccb-4535-9934-5bf0195bd7f0.png)
